"""Receipt photos: what happens to an image between the camera and the disk.

Nothing the browser sends is stored as it arrived. Every upload is decoded,
re-encoded and written under a name this app chose, which settles three separate
problems at once — a filename that walks out of the uploads folder, a file that
claims to be a JPEG and is not, and a 12-megapixel original that costs a phone
four seconds to load over Tailscale.

**EXIF is stripped, and that is the point.** A photo taken on a phone carries
the GPS coordinates of wherever you were standing, plus the device model and the
capture time. A receipt for a pharmacy purchase is a fairly private thing on its
own; the same file annotated with the pharmacy's exact location is a different
thing entirely, and neither the household nor anyone who ever gets a copy of the
backup has a use for it. So the pixels are copied into a fresh image and the
metadata is left behind rather than filtered — a blocklist of tags is a list
somebody has to keep current, and this is not.

Orientation is the one tag that means something, and it is applied to the pixels
before it is dropped, so a photo taken sideways stays the right way up.

Files live at `uploads/YYYY/MM/<uuid>.jpg`, dated by when they were uploaded
rather than when the purchase happened. Backfilling six weeks of receipts should
not scatter them across six folders, and the transaction row already knows the
date that matters.
"""

from __future__ import annotations

import io
import uuid
from datetime import datetime, timezone
from pathlib import Path

from flask import current_app

from db import execute, get_db, query, query_one, utc_now

# The long edge of the stored image. A receipt is read, not enlarged: 1600px is
# comfortably enough to make small print legible on a phone at full zoom, and it
# turns a 4MB camera original into roughly 300KB. On a Pi serving over a phone
# connection that difference is the whole experience.
MAX_EDGE = 1600

# The gallery on the edit page. Small enough that eight of them cost less than
# one full-size photo.
THUMB_EDGE = 320

# JPEG quality. 85 is the usual place to stop: above it the file grows faster
# than the picture improves, below it the small print on a till slip starts to
# smear, which is the one thing a receipt photo is for.
JPEG_QUALITY = 85

# What Pillow may hand back for us to keep. Anything else it can decode — BMP,
# TIFF, a GIF someone screenshotted — is re-encoded to JPEG rather than refused,
# because the person is standing at a till and "wrong file type" is not a
# problem they want to solve right now.
#
# PNG survives as PNG on purpose: a screenshot of a bank transfer confirmation is
# a real receipt in this household, and JPEG turns its text into mush.
_KEEP_FORMAT = {"PNG": ("PNG", ".png", "image/png")}
_DEFAULT_FORMAT = ("JPEG", ".jpg", "image/jpeg")

# HEIC, which is what an iPhone shoots by default, is deliberately not handled:
# decoding it needs pillow-heif, a second compiled dependency, and Safari already
# converts to JPEG when a photo is attached to a form. If that ever stops being
# true the fix is one package, not a redesign — hence the plain sentence below
# rather than a silent failure.
UNREADABLE = (
    "That file could not be read as an image. If it came from an iPhone as HEIC, "
    "take the photo again from inside the app or share it as JPEG."
)


class ReceiptError(ValueError):
    """A problem worth showing the person who just took the photo."""


# --------------------------------------------------------------- filesystem


def upload_root() -> Path:
    return Path(current_app.config["UPLOAD_DIR"])


def absolute(relative_path: str) -> Path:
    """Resolve a stored path, refusing anything that leaves the uploads folder.

    Every path in `attachments` was generated by this module, so in practice
    this can only fail if the database has been edited by hand. It is checked
    anyway: the alternative is a file-serving route whose safety rests on an
    assumption about a text column.
    """
    root = upload_root().resolve()
    target = (root / relative_path).resolve()
    if target != root and root not in target.parents:
        raise ReceiptError("That file is not where it says it is.")
    return target


def _month_folder() -> tuple[Path, str]:
    """(absolute folder, its path relative to uploads/), created if missing."""
    stamp = datetime.now(timezone.utc).strftime("%Y/%m")
    folder = upload_root() / stamp
    folder.mkdir(parents=True, exist_ok=True)
    return folder, stamp


# ------------------------------------------------------------------ imaging


def _strip_and_fit(raw: bytes) -> tuple[bytes, bytes, str, str]:
    """Decode, orient, strip metadata, resize. Returns (full, thumb, ext, mime).

    The stripping is the `Image.new` + `paste` in the middle. Pillow keeps a
    decoded image's metadata in `.info` and carries it through operations like
    `resize()`; pasting the pixels into a blank image of the same size leaves all
    of it behind in one step, at C speed. Saving without an `exif=` argument then
    writes a file that has never had metadata in it, rather than one that had it
    removed.
    """
    from PIL import Image, ImageOps, UnidentifiedImageError

    try:
        source = Image.open(io.BytesIO(raw))
        source.load()
    except Image.DecompressionBombError:
        raise ReceiptError("That image is far too large to be a receipt.") from None
    except (UnidentifiedImageError, OSError, ValueError):
        raise ReceiptError(UNREADABLE) from None

    # Read before anything else touches the image: every Pillow operation
    # returns a *new* object with `.format` set to None, so asking later gets
    # you None and turns every PNG into a JPEG.
    keep = _KEEP_FORMAT.get((source.format or "").upper())
    fmt, ext, mime = keep or _DEFAULT_FORMAT

    # Orientation is the one EXIF tag that changes what you see, so it is spent
    # on the pixels before the rest is discarded. Do this after the strip and a
    # photo taken sideways is stored sideways, permanently.
    source = ImageOps.exif_transpose(source)

    if fmt == "JPEG":
        # JPEG has no alpha channel, and a PNG with transparency saved as one
        # goes black where it was clear. Flatten onto white, which is what a
        # scanned slip looks like anyway.
        if source.mode in ("RGBA", "LA", "P"):
            source = source.convert("RGBA")
            flat = Image.new("RGB", source.size, (255, 255, 255))
            flat.paste(source, mask=source.split()[-1])
            source = flat
        elif source.mode != "RGB":
            source = source.convert("RGB")

    clean = Image.new(source.mode, source.size)
    clean.paste(source)

    full = clean.copy()
    full.thumbnail((MAX_EDGE, MAX_EDGE), Image.LANCZOS)
    thumb = clean.copy()
    thumb.thumbnail((THUMB_EDGE, THUMB_EDGE), Image.LANCZOS)

    def encode(image) -> bytes:
        buffer = io.BytesIO()
        if fmt == "JPEG":
            # optimize rebuilds the Huffman tables; progressive means a slow
            # connection shows a blurry whole receipt before a sharp top third.
            image.save(buffer, "JPEG", quality=JPEG_QUALITY, optimize=True, progressive=True)
        else:
            image.save(buffer, "PNG", optimize=True)
        return buffer.getvalue()

    return encode(full), encode(thumb), ext, mime


# -------------------------------------------------------------------- store


def store(transaction_id: int, upload) -> dict:
    """Attach one photo to one transaction. Returns the new attachment row.

    `upload` is a Werkzeug FileStorage, or anything with `.read()`. Its
    `filename` is read only to notice that a file was actually chosen — an empty
    file input still posts, with an empty name — and is never used on disk.

    Attaching clears `receiptless`, in the same database transaction. That is the
    agreed resolution of the contradiction rather than an incidental tidy-up: the
    photo is evidence and the flag was a claim, so the evidence wins. The trigger
    in migration 005 refuses the reverse.
    """
    raw = upload.read()
    if not raw:
        raise ReceiptError("That file was empty.")

    data, thumb_data, ext, mime = _strip_and_fit(raw)

    folder, stamp = _month_folder()
    name = uuid.uuid4().hex
    file_rel = f"{stamp}/{name}{ext}"
    thumb_rel = f"{stamp}/{name}-t{ext}"

    (folder / f"{name}{ext}").write_bytes(data)
    (folder / f"{name}-t{ext}").write_bytes(thumb_data)

    conn = get_db()
    try:
        # The flag first, so the insert's own trigger sees a transaction that no
        # longer claims to have no receipt. Both statements commit together, or
        # neither does.
        conn.execute(
            "UPDATE transactions SET receiptless = 0 WHERE id = ? AND receiptless = 1",
            (transaction_id,),
        )
        cur = conn.execute(
            "INSERT INTO attachments (transaction_id, file_path, thumb_path, mime, "
            "byte_size, created_at) VALUES (?,?,?,?,?,?)",
            (transaction_id, file_rel, thumb_rel, mime, len(data), utc_now()),
        )
        conn.commit()
    except Exception:
        conn.rollback()
        # The rows are gone; the files would otherwise stay. Nothing points at
        # them yet, so unlinking here is safe and skips the orphan table.
        for path in (folder / f"{name}{ext}", folder / f"{name}-t{ext}"):
            path.unlink(missing_ok=True)
        raise ReceiptError("That photo could not be attached.") from None

    return {
        "id": cur.lastrowid, "transaction_id": transaction_id,
        "file_path": file_rel, "thumb_path": thumb_rel,
        "mime": mime, "byte_size": len(data),
    }


def for_transaction(transaction_id: int) -> list:
    return query(
        "SELECT id, transaction_id, file_path, thumb_path, mime, byte_size, created_at "
        "FROM attachments WHERE transaction_id = ? ORDER BY id",
        (transaction_id,),
    )


def counts_for(transaction_ids) -> dict[int, int]:
    """How many photos each of these transactions has.

    One query for a whole page of the list rather than one per row: the entries
    screen draws fifty of them, and fifty round trips to answer "is there a
    paperclip on this line" is how a list gets slow on an SD card.
    """
    ids = list(transaction_ids)
    if not ids:
        return {}
    marks = ",".join("?" for _ in ids)
    return {
        row["transaction_id"]: row["n"]
        for row in query(
            f"SELECT transaction_id, COUNT(*) AS n FROM attachments "
            f"WHERE transaction_id IN ({marks}) GROUP BY transaction_id",
            ids,
        )
    }


def remove(attachment_id: int) -> bool:
    """Delete one photo. The caller has already decided the person may.

    Permission is not checked here on purpose. Whether someone may change a
    transaction is `visibility.can_edit()`, it is asked in the route, and a
    second half-answer in this module would be a second place for the rule to
    drift.
    """
    row = query_one("SELECT id FROM attachments WHERE id = ?", (attachment_id,))
    if row is None:
        return False
    execute("DELETE FROM attachments WHERE id = ?", (attachment_id,))
    reap()
    return True


# --------------------------------------------------------------------- reap


def reap(limit: int = 500) -> int:
    """Unlink the files that deleted rows left behind. Returns how many went.

    Safe to call at any time and safe to call twice: a path that is already gone
    is still a debt paid. It runs after a delete in the request, and again from
    `flask sweep-uploads` for anything a crash left in the table.

    A missing file clears its row rather than being retried forever — the row
    exists to make sure nothing is *forgotten*, not to insist the filesystem
    prove it.
    """
    rows = query("SELECT id, path FROM orphaned_files ORDER BY id LIMIT ?", (limit,))
    if not rows:
        return 0

    done: list[int] = []
    for row in rows:
        try:
            absolute(row["path"]).unlink(missing_ok=True)
        except (ReceiptError, OSError):
            # A path that will not resolve is never going to, and leaving it in
            # the table would stall every later reap behind it.
            pass
        done.append(row["id"])

    conn = get_db()
    conn.execute(
        f"DELETE FROM orphaned_files WHERE id IN ({','.join('?' for _ in done)})", done
    )
    conn.commit()

    # Folders empty themselves as a month's receipts are deleted. Left alone
    # they accumulate as a directory tree of nothing, which makes `ls` on the
    # uploads folder useless for seeing what is actually there.
    _prune_empty_folders()
    return len(done)


def _prune_empty_folders() -> None:
    root = upload_root()
    for month in sorted(root.glob("*/*"), reverse=True):
        if month.is_dir() and not any(month.iterdir()):
            month.rmdir()
    for year in sorted(root.glob("*")):
        if year.is_dir() and not any(year.iterdir()):
            year.rmdir()
